name: Ahoy Development

on:
  push:
    branches: development*
    paths-ignore:
    - '**.md' # Do no build on *.md changes
  workflow_call:
  workflow_dispatch:

jobs:
  check:
    name: Check Repository
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

  build-en:
    name: Build (EN)
    needs: check
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        variant:
          - opendtufusion
          - opendtufusion-16MB
          - esp8266
          - esp8266-all
          - esp8266-minimal
          - esp8266-prometheus
          - esp8285
          - esp32-wroom32
          - esp32-wroom32-minimal
          - esp32-wroom32-prometheus
          - esp32-s2-mini
          - esp32-c3-mini
    steps:
    - uses: actions/checkout@v4
    - uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 7

    - name: Cache Pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install PlatformIO
      run: |
        python -m pip install setuptools --upgrade pip
        pip install --upgrade platformio

    - name: Run PlatformIO
      run:  pio run -d src -e ${{ matrix.variant }}

    - name: Compress .elf
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -t7z -mx=9 src/.pio/build/${{ matrix.variant }}/firmware.elf.7z ./src/.pio/build/${{ matrix.variant }}/firmware.elf

    - name: Rename Firmware
      run: python scripts/getVersion.py ${{ matrix.variant }} >> $GITHUB_OUTPUT

    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev-${{ matrix.variant }}
        path: firmware/*
